### ISSUE TITLE
usage of deprecated tough-cookie version

### ISSUE THREAD

**Issue by Shoplifter** [SAPikachu/icomoon-build#10]
when I installed icomoon-build (globally), I got this warning:
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie 

https://nodesecurity.io/advisories/130 
recommends an update to v. 2.3.0 - is that possible?

**Comment by SAPikachu** [comment]
Upgraded phantomjs and it is gone. Can you try the latest version?

**Comment by Shoplifter** [comment]
It works perfectly now. Thanks a lot for that quick response.

**Comment by Shoplifter** [comment]
Sorry, my response was too early.
Only installation worked.
```
C:\Users\xxx\AppData\Roaming\npm\icomoon-build -> C:\Users\xxx\AppData\Roaming\npm\node_modules\icomoon-build\bin\icomoon-build
C:\Users\xxx\AppData\Roaming\npm
`-- icomoon-build@0.2.5
  `-- phantomjs-prebuilt@2.1.12
    `-- fs-extra@0.30.0
      `-- rimraf@2.5.4
        `-- glob@7.0.6
```
But running the script gives me this error:
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'phantomjs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\icomoon-build\lib\icomoon.js:9:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by SAPikachu** [comment]
Sorry, didn't catch this issue yesterday.. Just fixed, can you try again?

**Comment by Shoplifter** [comment]
Works now. Thank you very much!

(I ran into another problem thoug, but that is a different issue i guess.)
